language: cpp


compiler:
  - gcc
  - clang

os:
  - linux


sudo: false


env:
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DWITH_ITK=false" 

addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
   - libboost-dev
    - libcairo2-dev
    - libboost-system-dev
    - libboost-program-options-dev
    - libgmp-dev
    - libgdcm2-dev
    - libgraphicsmagick++1-dev
    - libqglviewer-dev
    - libinsighttoolkit3-dev
    - libfftw3-dev
    - g++-5
    - ninja-build
    - doxygen
    - graphviz
    - flex
    - bison
    - texlive

before_install:
  - env
  - export SRC_DIR="`pwd`"


before_script:
  - 'echo "using gcc : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" > ~/user-config.jam'
  - 'echo "using clang : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" >> ~/user-config.jam'
  - cd $SRC_DIR
  - git clone git://github.com/DGtal-team/DGtal.git
  - cd DGtal
  - cmake . $DGTALTYPE  -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER -DBOOST_ROOT=$BOOST_ROOT
  - make 
  - cd ..

script: 
  - cmake . -DCMAKE_BUILD_TYPE=Debug -DDGtal_DIR=$PWD/DGtal -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER
  - make
